apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
        - name: vprofile-app
          image: 060347994451.dkr.ecr.ap-south-1.amazonaws.com/devops:vprofileapp--%version%
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-credentials # This should be the name of the secret containing ECR credentials