---
- name: Build Artifact
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build with Maven and tests
      command: mvn clean package 

    - name: Copy artifact to Docker folder
      command: cp target/vprofile-1.0.6.war Docker-files/app/


    - name: Build Docker image
      command: docker build -t 484472757370.dkr.ecr.ap-south-1.amazonaws.com/vprofile-qa:vprofileapp-{{ version }} .
      args:
        chdir: /Docker-files/app

    - name: Docker login to ECR
      command: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 484472757370.dkr.ecr.ap-south-1.amazonaws.com

    - name: Push Docker image to ECR
      command: docker push 484472757370.dkr.ecr.ap-south-1.amazonaws.com/vprofile-qa:vprofileapp-{{ version }}

    - name: Update deployment.yaml
      replace:
        path: /var/lib/jenkins/workspace/vprofile-enterprise/eks-files/vapp/deployment.yaml
        regexp: '%version%'
        replace: '{{ version }}'

    - name: Set namespace based on DEPLOY_ENV
      set_fact:
        namespace: "{{ lookup('dict', {'QA': 'vprofile-eks-qa', 'Stage': 'vprofile-eks-stage', 'Prod': 'vprofile-eks-prod'})[DEPLOY_ENV] }}"
      when: DEPLOY_ENV in ['QA', 'Stage', 'Prod']

    - name: Apply vapp and vdb manifests
      command: kubectl apply -f /eks-files/{{ item }}/ -n {{ namespace }}
      with_items:
        - vapp
        - vdb
      when: namespace is defined